[variables]
NODE_OPTIONS = "--max-old-space-size=4096"
NPM_CONFIG_LEGACY_PEER_DEPS = "true"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_AUDIT = "false"

[phases.install]
cmds = [
  "npm install",
  "cd ../client && npm install"
]

[phases.build]
cmds = [
  "cd ../client && npm run build",
  "npx prisma generate && npm run build"
]
