[phases.install]
cmds = [
  "npm cache clean --force",
  "NODE_OPTIONS='--max-old-space-size=4096' npm install --legacy-peer-deps --no-fund --no-audit"
]

[phases.build]
cmds = ["npx prisma generate && npm run build"]
