import { PrismaClient, TitleType } from '@prisma/client';
import 'dotenv/config';
const prisma = new PrismaClient();
const platforms = [
    { name: 'Netflix', abbr: 'NF' },
    { name: 'Prime Video', abbr: 'PV' },
    { name: 'Hotstar', abbr: 'HS' },
    { name: 'JioCinema', abbr: 'JC' },
    { name: 'Apple TV+', abbr: 'AT' },
    { name: 'Zee5', abbr: 'Z5' },
    { name: 'Sony LIV', abbr: 'SL' },
    { name: 'Crunchyroll', abbr: 'CR' },
    { name: 'YouTube Movies', abbr: 'YT' },
    { name: 'MUBI', abbr: 'MU' },
];
const titles = [
    // ── Movies ──────────────────────────────────────────────────────────────
    { tmdbId: 872585, name: 'Oppenheimer', type: TitleType.MOVIE, year: 2023, runtimeMinutes: 180, genres: ['Biography', 'Drama', 'History'], synopsis: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.', posterColorFrom: '#1a1510', posterColorTo: '#0a0908', trailerYoutubeId: 'uYPbbksJxIg', platforms: ['NF', 'PV'] },
    { tmdbId: 693134, name: 'Dune: Part Two', type: TitleType.MOVIE, year: 2024, runtimeMinutes: 166, genres: ['Sci-Fi', 'Adventure', 'Drama'], synopsis: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against those who destroyed his family.', posterColorFrom: '#1c1410', posterColorTo: '#0a0807', trailerYoutubeId: 'Way9e1Q3JGc', platforms: ['PV', 'HS'] },
    { tmdbId: 792307, name: 'Poor Things', type: TitleType.MOVIE, year: 2023, runtimeMinutes: 141, genres: ['Comedy', 'Drama', 'Sci-Fi'], synopsis: 'The incredible tale and fantastical evolution of Bella Baxter, a young woman brought back to life by an unorthodox scientist.', posterColorFrom: '#1a1018', posterColorTo: '#0a0708', trailerYoutubeId: 'Zz3TJ2H5VSU', platforms: ['HS', 'JC'] },
    { tmdbId: 414906, name: 'The Batman', type: TitleType.MOVIE, year: 2022, runtimeMinutes: 176, genres: ['Action', 'Crime', 'Drama'], synopsis: 'When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate.', posterColorFrom: '#101018', posterColorTo: '#07070a', trailerYoutubeId: 'mqqft2x_AaQ', platforms: ['PV', 'HS'] },
    { tmdbId: 545611, name: 'Everything Everywhere All at Once', type: TitleType.MOVIE, year: 2022, runtimeMinutes: 139, genres: ['Action', 'Adventure', 'Comedy'], synopsis: 'A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save the world.', posterColorFrom: '#181020', posterColorTo: '#0a080c', trailerYoutubeId: 'wxL8bVg1uIQ', platforms: ['PV', 'MU'] },
    { tmdbId: 569094, name: 'Spider-Man: Across the Spider-Verse', type: TitleType.MOVIE, year: 2023, runtimeMinutes: 140, genres: ['Animation', 'Action', 'Adventure'], synopsis: 'Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its existence.', posterColorFrom: '#101820', posterColorTo: '#080a0c', trailerYoutubeId: 'cqGjhVJWtEg', platforms: ['NF', 'PV'] },
    { tmdbId: 1075794, name: 'Past Lives', type: TitleType.MOVIE, year: 2023, runtimeMinutes: 105, genres: ['Drama', 'Romance'], synopsis: 'Nora and Hae Sung, two deeply connected childhood friends, are reunited for one fateful week in New York.', posterColorFrom: '#1a1810', posterColorTo: '#0a0908', trailerYoutubeId: 'kO4Nl6G1LY8', platforms: ['PV'] },
    { tmdbId: 878977, name: 'Anatomy of a Fall', type: TitleType.MOVIE, year: 2023, runtimeMinutes: 152, genres: ['Crime', 'Drama', 'Thriller'], synopsis: 'A woman is suspected of her husband\'s murder, and their blind son faces a moral dilemma as the main witness.', posterColorFrom: '#151820', posterColorTo: '#0a0b0c', trailerYoutubeId: 'CZ7wP8U8w6I', platforms: ['PV', 'MU'] },
    { tmdbId: 861988, name: 'The Zone of Interest', type: TitleType.MOVIE, year: 2023, runtimeMinutes: 105, genres: ['Drama', 'History', 'War'], synopsis: 'The commandant of Auschwitz, Rudolf Höss, and his wife Hedwig strive to build a dream life for their family in a house next to the camp.', posterColorFrom: '#101810', posterColorTo: '#080a08', trailerYoutubeId: 'rB8eL7A1xXc', platforms: ['PV', 'MU'] },
    { tmdbId: 466420, name: 'Killers of the Flower Moon', type: TitleType.MOVIE, year: 2023, runtimeMinutes: 206, genres: ['Crime', 'Drama', 'History'], synopsis: 'Real love crosses paths with unspeakable betrayal as Mollie Burkhart fights for survival in 1920s Oklahoma.', posterColorFrom: '#1c1410', posterColorTo: '#0a0807', trailerYoutubeId: 'EP34Y1dPq4M', platforms: ['AT', 'PV'] },
    { tmdbId: 346698, name: 'Barbie', type: TitleType.MOVIE, year: 2023, runtimeMinutes: 114, genres: ['Adventure', 'Comedy', 'Fantasy'], synopsis: 'Barbie suffers a crisis that leads her to question her world and her existence.', posterColorFrom: '#201018', posterColorTo: '#0c0808', trailerYoutubeId: 'pBk4NYhWNMM', platforms: ['PV', 'HS'] },
    { tmdbId: 575264, name: 'Mission: Impossible – Dead Reckoning', type: TitleType.MOVIE, year: 2023, runtimeMinutes: 163, genres: ['Action', 'Adventure', 'Thriller'], synopsis: 'Ethan Hunt and his IMF team must track down a terrifying new weapon that threatens all of humanity.', posterColorFrom: '#101420', posterColorTo: '#080a0c', trailerYoutubeId: 'avz06PDqDmM', platforms: ['PV', 'HS'] },
    { tmdbId: 603692, name: 'John Wick: Chapter 4', type: TitleType.MOVIE, year: 2023, runtimeMinutes: 169, genres: ['Action', 'Crime', 'Thriller'], synopsis: 'John Wick uncovers a path to defeating The High Table, but before he can earn his freedom, he must face a new enemy.', posterColorFrom: '#101010', posterColorTo: '#080808', trailerYoutubeId: 'qEV9qF6hJJw', platforms: ['PV', 'HS'] },
    { tmdbId: 76600, name: 'Avatar: The Way of Water', type: TitleType.MOVIE, year: 2022, runtimeMinutes: 192, genres: ['Action', 'Adventure', 'Fantasy'], synopsis: 'Jake Sully lives with his newfound family formed on the extrasolar moon Pandora, but a familiar threat returns.', posterColorFrom: '#0a1820', posterColorTo: '#060a0c', trailerYoutubeId: '5PSNL1qE6VY', platforms: ['HS', 'JC'] },
    { tmdbId: 361743, name: 'Top Gun: Maverick', type: TitleType.MOVIE, year: 2022, runtimeMinutes: 130, genres: ['Action', 'Drama'], synopsis: 'After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront the ghosts of his past.', posterColorFrom: '#101820', posterColorTo: '#080a0c', trailerYoutubeId: 'qSqVVswaRXQ', platforms: ['PV', 'HS'] },
    { tmdbId: 756999, name: 'The Fabelmans', type: TitleType.MOVIE, year: 2022, runtimeMinutes: 151, genres: ['Drama'], synopsis: 'Growing up in post-World War II Arizona, a young Sammy Fabelman discovers a shattering family secret.', posterColorFrom: '#1a1810', posterColorTo: '#0a0908', trailerYoutubeId: 'D31rZQlL64A', platforms: ['PV'] },
    { tmdbId: 803114, name: 'Tár', type: TitleType.MOVIE, year: 2022, runtimeMinutes: 158, genres: ['Drama', 'Music'], synopsis: 'Renowned musician Lydia Tár is days away from recording the symphony that will elevate her career.', posterColorFrom: '#101010', posterColorTo: '#080808', trailerYoutubeId: 'i2nG4lT2_pE', platforms: ['PV', 'MU'] },
    { tmdbId: 878917, name: 'Decision to Leave', type: TitleType.MOVIE, year: 2022, runtimeMinutes: 138, genres: ['Crime', 'Drama', 'Mystery'], synopsis: 'A detective investigating a man\'s death in the mountains meets the dead man\'s mysterious wife.', posterColorFrom: '#101820', posterColorTo: '#080a0c', trailerYoutubeId: 'JkPdky9eD3w', platforms: ['MU'] },
    { tmdbId: 759727, name: 'RRR', type: TitleType.MOVIE, year: 2022, runtimeMinutes: 187, genres: ['Action', 'Drama'], synopsis: 'A fictitious story about two legendary revolutionaries and their journey away from home before they started fighting for their country.', posterColorFrom: '#201008', posterColorTo: '#0c0604', trailerYoutubeId: 'f_vbAtFSEc0', platforms: ['NF'] },
    { tmdbId: 785084, name: 'The Whale', type: TitleType.MOVIE, year: 2022, runtimeMinutes: 117, genres: ['Drama'], synopsis: 'A reclusive English teacher attempts to reconnect with his estranged teenage daughter.', posterColorFrom: '#181410', posterColorTo: '#0a0807', trailerYoutubeId: 'D30r0CwtIKc', platforms: ['PV'] },
    // ── Series ───────────────────────────────────────────────────────────────
    { tmdbId: 136311, name: 'The Bear', type: TitleType.SERIES, year: 2022, runtimeMinutes: 30, genres: ['Comedy', 'Drama'], synopsis: 'A young chef from the fine dining world comes home to Chicago to run his family sandwich shop.', posterColorFrom: '#1a1810', posterColorTo: '#0a0908', trailerYoutubeId: 'gJjzE7P0eZ4', platforms: ['HS'] },
    { tmdbId: 113988, name: 'Severance', type: TitleType.SERIES, year: 2022, runtimeMinutes: 45, genres: ['Drama', 'Mystery', 'Sci-Fi'], synopsis: 'Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives.', posterColorFrom: '#101820', posterColorTo: '#080a0c', trailerYoutubeId: 'xEQP4VVjrB0', platforms: ['AT'] },
    { tmdbId: 63177, name: 'Succession', type: TitleType.SERIES, year: 2018, runtimeMinutes: 60, genres: ['Drama'], synopsis: 'The Roy family is known for controlling the biggest media and entertainment company in the world.', posterColorFrom: '#101010', posterColorTo: '#080808', trailerYoutubeId: 'bzSTpdcs0iw', platforms: ['HS'] },
    { tmdbId: 100088, name: 'The Last of Us', type: TitleType.SERIES, year: 2023, runtimeMinutes: 60, genres: ['Action', 'Adventure', 'Drama'], synopsis: 'Joel and Ellie, a pair connected through the harshness of the world they live in, are forced to endure brutal circumstances.', posterColorFrom: '#1a1010', posterColorTo: '#0a0808', trailerYoutubeId: 'uLtkt8BonwM', platforms: ['HS'] },
    { tmdbId: 94997, name: 'House of the Dragon', type: TitleType.SERIES, year: 2022, runtimeMinutes: 60, genres: ['Action', 'Adventure', 'Drama'], synopsis: 'An internal succession war within House Targaryen at the height of its power, 172 years before the birth of Daenerys Targaryen.', posterColorFrom: '#201008', posterColorTo: '#0c0604', trailerYoutubeId: 'DotnJ7tTA6I', platforms: ['HS'] },
    { tmdbId: 83867, name: 'Andor', type: TitleType.SERIES, year: 2022, runtimeMinutes: 50, genres: ['Action', 'Adventure', 'Drama'], synopsis: 'Prequel series to Star Wars\' Rogue One. In an era filled with danger, deception and intrigue, Cassian Andor embarks on a path that will turn him into a rebel hero.', posterColorFrom: '#101010', posterColorTo: '#080808', trailerYoutubeId: 'j5UX7pjgywQ', platforms: ['HS'] },
    { tmdbId: 110316, name: 'The White Lotus', type: TitleType.SERIES, year: 2021, runtimeMinutes: 60, genres: ['Comedy', 'Drama'], synopsis: 'Set in a tropical resort, it follows the exploits of various guests and employees over the span of a week.', posterColorFrom: '#1a1810', posterColorTo: '#0a0908', trailerYoutubeId: 'KrlMjS8C8J0', platforms: ['HS'] },
    { tmdbId: 122288, name: 'Yellowjackets', type: TitleType.SERIES, year: 2021, runtimeMinutes: 60, genres: ['Drama', 'Horror', 'Mystery'], synopsis: 'A wildly talented high school girls soccer team becomes the unlucky survivors of a plane crash deep in the Canadian wilderness.', posterColorFrom: '#101810', posterColorTo: '#080a08', trailerYoutubeId: '8bP1p2j8I8w', platforms: ['PV'] },
    { tmdbId: 114462, name: 'Slow Horses', type: TitleType.SERIES, year: 2022, runtimeMinutes: 50, genres: ['Drama', 'Thriller'], synopsis: 'Follows a team of British intelligence agents who serve as a dumping ground department of MI5 due to their career-ending mistakes.', posterColorFrom: '#101010', posterColorTo: '#080808', trailerYoutubeId: '6G3r8xP5HqI', platforms: ['AT'] },
    { tmdbId: 97546, name: 'Ted Lasso', type: TitleType.SERIES, year: 2020, runtimeMinutes: 30, genres: ['Comedy', 'Drama', 'Sport'], synopsis: 'American college football coach Ted Lasso heads to London to manage AFC Richmond, a struggling English Premier League football team.', posterColorFrom: '#101810', posterColorTo: '#080a08', trailerYoutubeId: '3u7EIiohs6U', platforms: ['AT'] },
    { tmdbId: 85803, name: 'The Morning Show', type: TitleType.SERIES, year: 2019, runtimeMinutes: 60, genres: ['Drama'], synopsis: 'An inside look at the lives of the people who help America wake up in the morning, exploring the challenges faced by the team.', posterColorFrom: '#101018', posterColorTo: '#08080c', trailerYoutubeId: '5nW9o6NPEvE', platforms: ['AT'] },
    { tmdbId: 93740, name: 'Foundation', type: TitleType.SERIES, year: 2021, runtimeMinutes: 60, genres: ['Drama', 'Sci-Fi'], synopsis: 'A complex saga of humans scattered on planets throughout the galaxy all living under the rule of the Galactic Empire.', posterColorFrom: '#0a1018', posterColorTo: '#06080c', trailerYoutubeId: 'X4QYV5KAQOg', platforms: ['AT'] },
    { tmdbId: 132966, name: 'Silo', type: TitleType.SERIES, year: 2023, runtimeMinutes: 45, genres: ['Drama', 'Mystery', 'Sci-Fi'], synopsis: 'Men and women live in a giant silo underground with several regulations which they believe are in place to protect them from the toxic world above.', posterColorFrom: '#101810', posterColorTo: '#080a08', trailerYoutubeId: '8KpKc3B_4xI', platforms: ['AT'] },
    { tmdbId: 174349, name: 'The Diplomat', type: TitleType.SERIES, year: 2023, runtimeMinutes: 50, genres: ['Drama', 'Thriller'], synopsis: 'In the midst of an international crisis, Kate Wyler is a career diplomat who lands a high-profile job she is not suited for.', posterColorFrom: '#101018', posterColorTo: '#08080c', trailerYoutubeId: '4XJQx7J8wQE', platforms: ['NF'] },
    { tmdbId: 42009, name: 'Black Mirror', type: TitleType.SERIES, year: 2011, runtimeMinutes: 60, genres: ['Drama', 'Mystery', 'Sci-Fi'], synopsis: 'An anthology series exploring a twisted, high-tech multiverse where humanity\'s greatest innovations and darkest instincts collide.', posterColorFrom: '#101010', posterColorTo: '#080808', trailerYoutubeId: '5jY1ECibHKY', platforms: ['NF'] },
    { tmdbId: 66732, name: 'Stranger Things', type: TitleType.SERIES, year: 2016, runtimeMinutes: 51, genres: ['Drama', 'Fantasy', 'Horror'], synopsis: 'When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces.', posterColorFrom: '#101820', posterColorTo: '#080a0c', trailerYoutubeId: 'b9EkMc79ZSU', platforms: ['NF'] },
    { tmdbId: 82856, name: 'The Mandalorian', type: TitleType.SERIES, year: 2019, runtimeMinutes: 40, genres: ['Action', 'Adventure', 'Fantasy'], synopsis: 'The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.', posterColorFrom: '#101010', posterColorTo: '#080808', trailerYoutubeId: 'aOC8E8z_ifw', platforms: ['HS'] },
    { tmdbId: 84958, name: 'Loki', type: TitleType.SERIES, year: 2021, runtimeMinutes: 50, genres: ['Action', 'Adventure', 'Fantasy'], synopsis: 'The mercurial villain Loki resumes his role as the God of Mischief in a new series that takes place after the events of Avengers: Endgame.', posterColorFrom: '#101820', posterColorTo: '#080a0c', trailerYoutubeId: 'nW948Va-l10', platforms: ['HS'] },
    { tmdbId: 85271, name: 'WandaVision', type: TitleType.SERIES, year: 2021, runtimeMinutes: 35, genres: ['Action', 'Comedy', 'Drama'], synopsis: 'Blends the style of classic sitcoms with the MCU, in which Wanda Maximoff and Vision live idealized suburban lives.', posterColorFrom: '#181018', posterColorTo: '#0a080c', trailerYoutubeId: 'sj9J2ecsSpo', platforms: ['HS'] },
    { tmdbId: 92749, name: 'Moon Knight', type: TitleType.SERIES, year: 2022, runtimeMinutes: 50, genres: ['Action', 'Adventure', 'Fantasy'], synopsis: 'Steven Grant discovers he has dissociative identity disorder and shares a body with mercenary Marc Spector.', posterColorFrom: '#101010', posterColorTo: '#080808', trailerYoutubeId: 'x7Krla_CxEc', platforms: ['HS'] },
    { tmdbId: 126308, name: 'Shōgun', type: TitleType.SERIES, year: 2024, runtimeMinutes: 60, genres: ['Action', 'Adventure', 'Drama'], synopsis: 'When a mysterious European ship is found marooned in a nearby fishing village, Lord Yoshii Toranaga discovers secrets that could tip the scales of power.', posterColorFrom: '#1a1010', posterColorTo: '#0a0808', trailerYoutubeId: 'yTKYdq2YpOQ', platforms: ['HS'] },
    { tmdbId: 106379, name: 'Fallout', type: TitleType.SERIES, year: 2024, runtimeMinutes: 60, genres: ['Action', 'Adventure', 'Drama'], synopsis: 'In an alternate history, people live in luxury fallout shelters to escape the radiation above.', posterColorFrom: '#1a1410', posterColorTo: '#0a0807', trailerYoutubeId: '0j2Rs3m0Z5I', platforms: ['AT'] },
    { tmdbId: 128960, name: 'The Penguin', type: TitleType.SERIES, year: 2024, runtimeMinutes: 60, genres: ['Crime', 'Drama'], synopsis: 'Following the events of The Batman, Oz Cobb, a.k.a. the Penguin, makes a play to seize the reins of the crime world in Gotham.', posterColorFrom: '#101010', posterColorTo: '#080808', trailerYoutubeId: 'c8TJB5OIXME', platforms: ['HS'] },
    // ── Anime ────────────────────────────────────────────────────────────────
    { tmdbId: 95479, name: 'Jujutsu Kaisen', type: TitleType.ANIME, year: 2020, runtimeMinutes: 24, genres: ['Animation', 'Action', 'Adventure'], synopsis: 'A boy swallows a cursed talisman and enters a shaman\'s school to be able to locate the demon\'s own body parts.', posterColorFrom: '#101820', posterColorTo: '#080a0c', trailerYoutubeId: 'yILd5y1XJqQ', platforms: ['CR', 'NF'] },
    { tmdbId: 85937, name: 'Demon Slayer', type: TitleType.ANIME, year: 2019, runtimeMinutes: 24, genres: ['Animation', 'Action', 'Adventure'], synopsis: 'A family is attacked by demons and only two members survive. The survivor makes it his mission to hunt down the demons.', posterColorFrom: '#201008', posterColorTo: '#0c0604', trailerYoutubeId: 'vFF6NUx9rQo', platforms: ['CR', 'NF'] },
    { tmdbId: 1429, name: 'Attack on Titan', type: TitleType.ANIME, year: 2013, runtimeMinutes: 24, genres: ['Animation', 'Action', 'Adventure'], synopsis: 'After his hometown is destroyed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans.', posterColorFrom: '#101010', posterColorTo: '#080808', trailerYoutubeId: 'Mgr0TL5jfdU', platforms: ['CR', 'NF'] },
    { tmdbId: 139021, name: 'Spy x Family', type: TitleType.ANIME, year: 2022, runtimeMinutes: 24, genres: ['Animation', 'Action', 'Comedy'], synopsis: 'A spy on an undercover mission gets married and adopts a child as part of his cover, not knowing his wife and daughter have their own secrets.', posterColorFrom: '#101820', posterColorTo: '#080a0c', trailerYoutubeId: '6sRzR1wF1xI', platforms: ['CR', 'NF'] },
    { tmdbId: 114410, name: 'Chainsaw Man', type: TitleType.ANIME, year: 2022, runtimeMinutes: 24, genres: ['Animation', 'Action', 'Adventure'], synopsis: 'Following a betrayal, a young man is reborn as a devil-human hybrid and seeks revenge.', posterColorFrom: '#201008', posterColorTo: '#0c0604', trailerYoutubeId: 'v4yLe6kTV0Y', platforms: ['CR'] },
    { tmdbId: 209544, name: 'Blue Eye Samurai', type: TitleType.ANIME, year: 2023, runtimeMinutes: 50, genres: ['Animation', 'Action', 'Adventure'], synopsis: 'Driven by a dream of bloody revenge, a mixed-race master of the sword lives a life in disguise in Edo-period Japan.', posterColorFrom: '#101820', posterColorTo: '#080a0c', trailerYoutubeId: 'wQakmzTYMAY', platforms: ['NF'] },
    { tmdbId: 125424, name: 'Cyberpunk: Edgerunners', type: TitleType.ANIME, year: 2022, runtimeMinutes: 24, genres: ['Animation', 'Action', 'Adventure'], synopsis: 'A street kid tries to survive in a technology and body modification-obsessed city of the future.', posterColorFrom: '#101018', posterColorTo: '#08080c', trailerYoutubeId: 'pMYOPSSqN8Y', platforms: ['NF'] },
    { tmdbId: 94605, name: 'Arcane', type: TitleType.ANIME, year: 2021, runtimeMinutes: 40, genres: ['Animation', 'Action', 'Adventure'], synopsis: 'Set in Utopian Piltover and the oppressed underground of Zaun, the story follows the origins of two iconic League champions.', posterColorFrom: '#101820', posterColorTo: '#080a0c', trailerYoutubeId: 'fXmAur31yzk', platforms: ['NF'] },
    { tmdbId: 87600, name: 'Vinland Saga', type: TitleType.ANIME, year: 2019, runtimeMinutes: 24, genres: ['Animation', 'Action', 'Adventure'], synopsis: 'Thorfinn pursues a journey with his father\'s killer in order to take revenge and end his life in a duel as an honorable warrior.', posterColorFrom: '#1a1410', posterColorTo: '#0a0807', trailerYoutubeId: 'K6exFgMsxG4', platforms: ['CR', 'NF'] },
    { tmdbId: 127141, name: 'Ousama Ranking', type: TitleType.ANIME, year: 2021, runtimeMinutes: 24, genres: ['Animation', 'Adventure', 'Comedy'], synopsis: 'The people of the kingdom look down on the young prince Bojji due to his deafness and small stature, but he dreams of becoming a great king.', posterColorFrom: '#1a1810', posterColorTo: '#0a0908', trailerYoutubeId: 'TRCvCz0XPSA', platforms: ['CR'] },
    { tmdbId: 209867, name: 'Frieren: Beyond Journey\'s End', type: TitleType.ANIME, year: 2023, runtimeMinutes: 24, genres: ['Animation', 'Adventure', 'Drama'], synopsis: 'An elf mage reflects on her journey with a legendary hero party after their quest ends and the hero passes away.', posterColorFrom: '#101820', posterColorTo: '#080a0c', trailerYoutubeId: 'yxg5hxOEFcs', platforms: ['CR'] },
    { tmdbId: 187453, name: 'Oshi no Ko', type: TitleType.ANIME, year: 2023, runtimeMinutes: 24, genres: ['Animation', 'Drama', 'Fantasy'], synopsis: 'A doctor and his recently-deceased patient are reborn as twins to a famous Japanese pop idol and navigate the highs and lows of the entertainment industry.', posterColorFrom: '#181018', posterColorTo: '#0a080c', trailerYoutubeId: 'ZpBfVrMVBZc', platforms: ['CR'] },
    { tmdbId: 202411, name: 'Heavenly Delusion', type: TitleType.ANIME, year: 2023, runtimeMinutes: 24, genres: ['Animation', 'Adventure', 'Mystery'], synopsis: 'In the outside world, fifteen years after the disaster, Maru and Kiruko search for a place called Heaven.', posterColorFrom: '#101810', posterColorTo: '#080a08', trailerYoutubeId: 'TnAcE3f7iMw', platforms: ['CR'] },
    { tmdbId: 122695, name: 'Hell\'s Paradise', type: TitleType.ANIME, year: 2023, runtimeMinutes: 24, genres: ['Animation', 'Action', 'Adventure'], synopsis: 'A squad of prisoners and their guards are sent to a mysterious island to retrieve the elixir of life.', posterColorFrom: '#101010', posterColorTo: '#080808', trailerYoutubeId: 'EJ3sI0C9KoU', platforms: ['CR'] },
    { tmdbId: 207930, name: 'The Apothecary Diaries', type: TitleType.ANIME, year: 2023, runtimeMinutes: 24, genres: ['Animation', 'Drama', 'Mystery'], synopsis: 'In the imperial court, a young girl with a mysterious past uses her knowledge of medicine to solve mysteries.', posterColorFrom: '#101018', posterColorTo: '#08080c', trailerYoutubeId: 'M5CUZIJ1lmE', platforms: ['CR'] },
    { tmdbId: 246063, name: 'Delicious in Dungeon', type: TitleType.ANIME, year: 2024, runtimeMinutes: 24, genres: ['Animation', 'Adventure', 'Comedy'], synopsis: 'A party of adventurers must eat the monsters they slay as they delve deeper into a dungeon to rescue their fallen comrade.', posterColorFrom: '#1a1410', posterColorTo: '#0a0807', trailerYoutubeId: 'QZCo5sZgdIQ', platforms: ['NF'] },
    { tmdbId: 232132, name: 'Solo Leveling', type: TitleType.ANIME, year: 2024, runtimeMinutes: 24, genres: ['Animation', 'Action', 'Adventure'], synopsis: 'In a world where hunters must battle deadly monsters to protect humanity, a weak hunter discovers a mysterious power.', posterColorFrom: '#101820', posterColorTo: '#080a0c', trailerYoutubeId: 'ZGgTfxm2mGE', platforms: ['CR'] },
    { tmdbId: 229266, name: 'Kaiju No. 8', type: TitleType.ANIME, year: 2024, runtimeMinutes: 24, genres: ['Animation', 'Action', 'Adventure'], synopsis: 'A man working for a kaiju cleanup company gains the ability to transform into a kaiju and must balance his new power with his ordinary life.', posterColorFrom: '#101810', posterColorTo: '#080a08', trailerYoutubeId: 'VBQiqNJyXe0', platforms: ['CR'] },
    { tmdbId: 242396, name: 'Wind Breaker', type: TitleType.ANIME, year: 2024, runtimeMinutes: 24, genres: ['Animation', 'Action'], synopsis: 'Haruka Sakura wants to fight his way to the top of his new school, only to discover it is a haven for those who protect the town.', posterColorFrom: '#101018', posterColorTo: '#08080c', trailerYoutubeId: 'z2dNiEPG7v0', platforms: ['CR'] },
    { tmdbId: 85937, name: 'Demon Slayer: Hashira Training Arc', type: TitleType.ANIME, year: 2024, runtimeMinutes: 24, genres: ['Animation', 'Action', 'Adventure'], synopsis: 'Tanjiro undergoes rigorous training with the Hashira to prepare for the final battle against Muzan Kibutsuji.', posterColorFrom: '#201008', posterColorTo: '#0c0604', trailerYoutubeId: 'VYkEbQk_yLU', platforms: ['CR'] },
];
async function main() {
    for (const p of platforms) {
        await prisma.platform.upsert({ where: { abbr: p.abbr }, update: {}, create: p });
    }
    const allPlatforms = await prisma.platform.findMany();
    for (const t of titles) {
        const title = await prisma.title.create({
            data: {
                name: t.name, type: t.type, year: t.year, runtimeMinutes: t.runtimeMinutes,
                genres: t.genres, synopsis: t.synopsis, posterColorFrom: t.posterColorFrom,
                posterColorTo: t.posterColorTo, trailerYoutubeId: t.trailerYoutubeId,
                tmdbId: t.tmdbId ?? undefined,
                officialWatchLinks: t.platforms.map(abbr => {
                    const plat = allPlatforms.find(p => p.abbr === abbr);
                    return { platform: plat?.name || abbr, url: '#' };
                }),
            },
        });
        for (const abbr of t.platforms) {
            const plat = allPlatforms.find(p => p.abbr === abbr);
            if (plat)
                await prisma.titlePlatform.create({ data: { titleId: title.id, platformId: plat.id } });
        }
    }
    console.log(`Seeded ${titles.length} titles and ${platforms.length} platforms.`);
}
main().catch(e => { console.error(e); process.exit(1); }).finally(async () => { await prisma.$disconnect(); });
