// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/categories/PremiumCategories.tsx": () => import("../components/mockups/categories/PremiumCategories.tsx"),
  "./components/mockups/allrated-home/Home.tsx": () => import("../components/mockups/allrated-home/Home.tsx")
};
